### ISSUE TITLE
Website layout is broken on a 13" display

### ISSUE THREAD

**Issue by timriley** [drnic/appscrolls#5]
The fixed text at the bottom of the sidebar overlaps the normal scroll-able sidebar content. See this screenshot:

http://cl.ly/1L3s3M0f2F3e3Z371l0K

I have a feeling this GitHub site template wasn't built to accommodate a lot of sidebar content like this.

One way to fix it is to move the "installation is simple" and "usage is simple" sections from the sidebar. Alternatively, move the fixed sidebar content ("This project is maintained by Dr Nic") and move it to the bottom of the main content section.

Let me know which you prefer and I'm happy to do it :)

**Comment by drnic** [comment]
Let's move the fixed stuff to the bottom of the main site. Thats not a priority for any first time visitors to App Scrolls. They don't care who made it until it works for them :) 

Thanks! 

Cheers
Nic

Dr Nic Williams - VP Engineering
Engine Yard
The Leading Platform as a Service
Mobile: +1 415 860 2185
Skype: nicwilliams
Twitter: @drnic

**Comment by drnic** [comment]
Fixed by #6
